{% set name = "octokit" %}
{% set version = "4.16.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 76c26da61478c866df8065966b5c7ca7bcc1956a24a27d0b2662168551117d1a

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-sawyer >=0.8.0,<0.9

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Simple wrapper for the GitHub API

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/octokit/{{ name }}.rb

extra:
  recipe-maintainers:
    - sodre
