travis:
  secure:
    BINSTAR_TOKEN: iGh7ZCaPi7OIxvhWh3U1x3GUlOBcFfZZnwLUAyN2sUP2Kj1t+dIZG2o7o43LINeDnfKyj+QGTBio+fiDf05HMCM8QJgDY/7H0Ja+Xl++oaSb6231JIIrpMdkLXa5uy2OGt0yW0iqAIwWJ3orYpuWet+C/Q8EmdEJnDrg/Z037LoKa207Aso8BkyXKkWLVKCh16WpR/NXgGUwRdJ02mM21+GEO47l1HY11Jt2Nd3Yal+eFsb8rVbhaSfbEIuybL+cnOcy86zDcgr+hSTVs899MdIKcwKjerMIUZ/Li0gElh3xGMct7m2Pcj+M8y10coJSTqvsTO+FdpzJiOnQUhGtEjeZf8CXc+rtDathNydcPq+CpOZT2n7DMns9jBGa4VXQUQ42xUqHxNCoFsmgwKdeH4hG3jriTtAY/6hBOSLL7j/ZTnpDwctZBNlgeQXsu5/DVTGSJAF6Mk4jLyC+/pDcok3jkLKk2PveFhCbkhoQWft3WUmMkKl+tuYDWKuZBIs/QtrRkm5BpVPVMg1NqOBi1Zx+QKTskY03D8o7zb2x4zfEYhsoYN2K09TDpwVqHCy/SiHHxqEuQ2/M4jITCjhb+7lQq7qmQqZLOHJ5npayoEI+Z1uVj8GT4P67PtVpBuoRgwYbeSQZjxxCj5MCGC9FdO/RBMcQFg5RLQPfLN9juNE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
