travis:
  secure:
    BINSTAR_TOKEN: c8PZ58pue3i8Xvmo9CvNrNxurlCagIIADH8uSsJ0a4C3XTaJbK3tRDehSzd3xjNIgITvoXSylTY+x1BipD89KB2wzbE/RdQ/hmykLG90kAEUUmnh+0Le3L90Sh8/NUa3tZBQbO+KBsvKkqN4Is0PglGoBDcj1tqz+gS6sVS6mZFIpl8D6l1+JhBEqXlY3cIh+LLdOyHRVuImA5d64WlJu3CkWAs1z5yRHTE4QXgqhalDZjeACtObSyhtja6i63ZY9/h6y4vdy45PfXTcxDNI+vpbxKO8cxDsn9B3EumWzqCGygfjS3T95FBlAToh8UWTmbl1urRpEwxtA/rDTA5bPnjqMXRb5xXY4CUysbbnxi+WcRXGLAm4k22/2qbxCKnEqsUsOVJRKdjWCwGi0PFbE71Ak66MCIiWlEywh3llkNXLNcN4LhsA93fkMIOck9VXCF+IdGGe4eQctHbBwuElrrxNmT5mFBeH40U14MBKJEE+Jzqm42WJXdLqq3oSD6Rx+hJ0t9KTmHFwYXgyYTyz7jcIoOA9GTBCuDkYyJZK50WAGhsKdS/GZDqeJmMMuAHDUGJP7WVsmju3388ZYkda4vWMlJE5OxDsTg3QZPIzOcdkhnu22zkwbTBSpLdMJ0cP3vACYZUUCbQtJB0KqFpS9KuOx9r3hBe7TlQXzlbCXzI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
